### ISSUE TITLE
Consider if BlockPosition and Location should have a World argument

### ISSUE THREAD

**Issue by Techcable** [FountainMC/FountainAPI#1]
Minecaraft's BlockPosition doesn't have a location, and it leads to code like this:

``` java
public default Block getBlockAt(BlockPosition pos) {
    checkNotNull(pos, "Null position");
    checkArgument(pos.getWorld() == this, "Position's world %s doesn't equal chunk's world %s", pos.getWorld().getName(), this.getName());
    return getBlockAt(pos.getX(), pos.getY(), pos.getZ());
}
```

However, Bukkit has World as part of their location, it could be useful to plugins, and is technically part of a 'Location'.

**Comment by phase** [comment]
If we're going to support multiple worlds, I think it is a must.

**Comment by Techcable** [comment]
Agreed, its very nice for plugins.
Its more important to make stuff easy for plugins than to make stuff easy for the implementation.
