### ISSUE TITLE
Use BlockState instead of Blocks

### ISSUE THREAD

**Issue by Techcable** [FountainMC/FountainAPI#2]
Blocks are a little extreme object oriented-wise.
CraftBlock is a inefficient utility object and has no corresponding object in the minecraft code.
Using BlockStates (like minecraft does), would make a lot more sense, would be more efficient.

I think it'd also be better for plugins since BlockStates are immutable and represent the actual data behind a block, not the block itself.
Since they'd be immutable they could also have an inheritance hierarchy and we can represent type-specific information with sub-interfaces. (Bukkit has this too but in a separate API added later as an afterthought)

**Comment by phase** [comment]
Seems like a nice plan.

**Comment by phase** [comment]
Closed in https://github.com/FountainMC/FountainAPI/commit/6b9a3b785dbcea66bdc3dda06c8453d6a4f26099

**Comment by phase** [comment]
The current implementation of BlockPosition (now renamed Block) doesn't have a way to obtain the block's id.

**Comment by phase** [comment]
Woah, no this is not closed. No clue what I was doing.

_This whole "3am programming" thing isn't working out so great._

**Comment by phase** [comment]
What should these BlockStates contain?

**Comment by 28andrew** [comment]
Maybe things similar to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/BlockState.html

**Comment by phase** [comment]
[Stash Link](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/block/BlockState.java)

That's what I had in mind, except their would only be on BlockState per coords.

**Comment by 28andrew** [comment]
Yeah, a "Block" in Spigot is represented by coords.

**Comment by Techcable** [comment]
Except that it shouldn't have coordinates, it should just represent a block's data.
I'm working on implementing all the block data (not tile entities) in minecraft right now.

**Comment by PizzaCrust** [comment]
So, BlockPosition represents a block's position inside of the World. And, the BlockState contains all of the data of the block?

**Comment by Techcable** [comment]
@PizzaCrust Yes, and since blocks can only have 16 values at max, there will only be 16 instances of a BlockState at max.

**Comment by PizzaCrust** [comment]
If the BlockStates are immutable, will it be so:
- Retrieve Block State, <- immutable
- Modify BlockState, but doesn't change it for reals.
- Set the BlockState on the BlockPosition

**Comment by Techcable** [comment]
Kinda like this:

``` java
BlockPosition position = new BlockPosition(world, x, y, z);
BlockState state = world.getBlock(position);
if (state instanceof PoweredBlock) {
    state = ((PoweredBlock) state).withPower(PoweredBlock.MAXIMUM_POWER); // Notice how this is a new object, and the existing state is the same
}
world.setBlock(position, state);
```

**Comment by phase** [comment]
How would I get an instance of a BlockState from an id and meta? I assume it's not

``` java
BlockState state = new BlockState(1, 3);
```

Will it be another World method?

``` java
BlockState grass = world.getBlockState(2);
```

**Comment by PizzaCrust** [comment]
@Techcable 

Nice!

**Comment by Techcable** [comment]
@phase It'd be a server method, since it doesn't need a world.

**Comment by PizzaCrust** [comment]
@Techcable your maven repository doesn't work on gradle.

**Comment by Techcable** [comment]
Fixed by a807df3913c69efedfd4644be7affba468823f81

**Comment by PizzaCrust** [comment]
How would one implement `getMaterial(String name)`, all I can think of is circularity issues.

**Comment by Techcable** [comment]
@PizzaCrust 
Good point, we might want to move them to 'VanillaMaterials'.

**Comment by PizzaCrust** [comment]
I think this Material class should just be a enum.

**Comment by Techcable** [comment]
@PizzaCrust We want to be able to eventually support mods 😉

**Comment by PizzaCrust** [comment]
Mods can add enums via reflection.

**Comment by Techcable** [comment]
@PizzaCrust We want to prevent [this](https://github.com/Techcable/Cauldron-Old/blob/master/src/main/java/net/minecraftforge/cauldron/entity/CraftCustomEntity.java)
We shouldn't use an enumeration when there is a possibility for additional items.

**Comment by PizzaCrust** [comment]
If the material class is a enum, they could do [this](https://github.com/MinecraftForge/MinecraftForge/blob/caa61e1be99a656abd667307f08324067d9bcda0/src/main/java/net/minecraftforge/common/util/EnumHelper.java#L219).

**Comment by phase** [comment]
We don't want mods to bend to our needs, we want plugins to. That's the problem MCPC had.
