### ISSUE TITLE
Refactor PluginManager into a interface

### ISSUE THREAD

**Issue by PizzaCrust** [FountainMC/FountainAPI#30]
I believe implementations should be able to create custom implementations of PluginManager, and that the current PluginManager class should be moved into a interface to make it the class more generic. The current implementation code should be moved into a class such as SimplePluginManager, similar to Bukkit.

**Comment by PizzaCrust** [comment]
Btw, is this project dead?

**Comment by minecrafter** [comment]
Yes, it is.
