### ISSUE TITLE
Command API

### ISSUE THREAD

**Issue by PizzaCrust** [FountainMC/FountainAPI#9]

**Comment by phase** [comment]
I'm a fan of annotations, so I was thinking of something like:

``` java
@Command(name = "test")
public void testCommad(String[] args, Sender sender) {
    sender.sendMessage("/test " + Arrays.toString(args));
}
```

And we could have some other options like

``` java
@Command(name = "othertest", sender = Player.class) {// Checks if sender is an instance of the class
}
```

To register the commands, we could add a method to Fountain or the Server.

``` java
@Plugin(id = "testCommands")
public class TestCommands {

    @EventHandler
    public void onEnable(ServerStartEvent event) {
        Fountain.getCommandManager().registerCommands(this);
    }

    @Command
    //...

}
```

**Comment by PizzaCrust** [comment]
Hmm, I'll create a pull request adding these API features.

**Comment by PizzaCrust** [comment]
Possibly, like this instead?

``` java
@Command(name = "test", allow = SenderType.PLAYER)
public void onCommandExecuted(CommandArguments arguments, Sender sender) {}
```

**CommandArguments** allows to merge and do additional parsing operations.

**Comment by phase** [comment]
CommandArguments could just hold the Sender.

**Comment by PizzaCrust** [comment]
@phase Good idea.

**Comment by phase** [comment]
I don't think that will work with the `allow` field. :confused:

**Comment by PizzaCrust** [comment]
Why?

**Comment by phase** [comment]
If Sender is a superinterface of Player and Console or whatever, then you'd have to cast it to the appropriate interface _in your code_. I think

``` java
@Command(allow = Player.class)
void command(String[] args, Player player){}
```

makes a lot more sense. You don't need to cast it to anything, nor we need an Enum. CommandArguments seems like a useless object.

**Comment by PizzaCrust** [comment]
Enums are much neater than using direct references to classes.

A player example.

``` java
@Command(name = "test", allow = SenderType.PLAYER)
void command(CommandInfo<Player> info) { Player player = info.getSender(); }
```

Console and player example.

``` java
@Command(name = "both")
void command(CommandInfo<Sender> info) { Sender sender = info.getSender(); }
```

CommandInfo provides parsing of arguments, and a direct instance to the sender using generics.
I think CommandInfo should be added, so it's neater. And, no casting.

**Comment by phase** [comment]
I didn't think about generics :dizzy_face:

I don't see the point of a wrapper object for only an array and another object. It makes more sense to put them as the method arguments, and it's easier for plugins to directly access the arguments instead of creating local variables for the CommandInfo fields.

``` java
void command(String[] args, Player player) {
    player.sendMessage(args[0]);
}

// vs

void command(CommandInfo<Player> info) {
    info.getSender().sendMessage(info.getArguments()[0]);
}

// or

void command(CommandInfo<Player> info) {
    Player player = info.getSender();
    String[] args = info.getArguments();
    // lots of logic which access the player and arguments a lot
}
```

**Comment by PizzaCrust** [comment]
CommandInfo also provides parsing utilities, which saves time.

``` java
void onMessageCommand(CommandInfo<Sender> info) { 
     String message = info.mergeArguments(0, info.getArguments().length);
     System.out.println(message);
}
```

Otherwise, the developer must do it manually:

``` java
void onMessageCommand(CommandInfo<Sender> info) {
       int currentIndex = startingIndex;
        StringBuilder builder = new StringBuilder();
        while (currentIndex != endIndex) {
            builder.append(array[currentIndex] + " ");
            currentIndex++;
        }
        return builder.toString().trim();
}
```

**Comment by phase** [comment]
Guava has support for String joining, and so does Java 8.

**Comment by PizzaCrust** [comment]
I'll fix that in a pull request in a moment.

**Comment by phase** [comment]
Closed in https://github.com/FountainMC/FountainAPI/commit/04db67509dffd5c9b61ad74a4bfec80f837ef2ed

**Comment by wgaylord** [comment]
Correct this allows to If I dynamicly add commands? If not we should add that ability.

**Comment by PizzaCrust** [comment]
yes if you do some bytecode generation and register the generated class, lol

**Comment by Techcable** [comment]
We want to discourage bytecode generation.......

**Comment by PizzaCrust** [comment]
@Techcable Ok, then there should be a new proposed API dealing with this.

**Comment by PizzaCrust** [comment]
Probably like this:

``` java
Fountain.getServer().getCommandManager().register(ICommand command);
```

**Comment by wgaylord** [comment]
Yeah because this is the one thing bukkit lacks. (And everyone uses reflection to back at.)

**Comment by PizzaCrust** [comment]
`BukkitCommand` is like `ICommand`. (in bukkit)
